spring:
  datasource:
    url: jdbc:mysql://10.42.29.120:3306?useSSL=false
    username: root
    password: music_online
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  typeAliasesPackage: com.dgut.music_online.dao
  mapperLocations: classpath:/mapper/*Mapper.xml

