spring:
  datasource:
    url: jdbc:mysql://10.42.29.120:3306?useSSL=false
    username: root
    password: music_online
    driver-class-name: com.mysql.jdbc.Driver
  # 配置文件上传
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
mybatis:
  typeAliasesPackage: com.dgut.music_online.dao
  mapperLocations: classpath:/mapper/*Mapper.xml

