spring:
  datasource:
    url: jdbc:mysql://172.28.7.36:3306?useSSL=false
    username: root
    password: music_online
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  typeAliasesPackage: com.dgut.music_online.dao
  mapperLocations: classpath:/mapper/*Mapper.xml

